### ISSUE TITLE
Plugin requires `dev` dependencies

### ISSUE THREAD

**Issue by bencroker** [verbb/timber#1]
### Describe the bug

The `composer.json` file has three `dev` dependencies which make it impossible to install without setting `"minimum-stability": "dev"`, which is obviously not desirable in a production environment.

```
    "require": {
        "php": "^8.0.2",
        "craftcms/cms": "^4.0.0",
        "nystudio107/craft-plugin-vite": "^4.0.0-beta.4",
        "workerman/phpsocket.io": "dev-master",
        "workerman/phpsocket.io-emitter": "dev-master",
        "verbb/base": "^2.0.0",
        "verbb/parallel-process": "dev-master",
        "yii2mod/yii2-array-query": "^1.4"
    },
```

You can see the full error at https://app.warp.dev/block/4ElpgL0xbUqR4NDo8iqthB

### Steps to reproduce

Run `composer require verbb/timber` in an environment without `"minimum-stability": "dev"`.

### Craft CMS version

4.3.10

### Plugin version

1.0.0

**Comment by engram-design** [comment]
Should be fixed in [1.0.1](https://github.com/verbb/timber/releases/tag/1.0.1)
