### ISSUE TITLE
AxiosError when trying to view custom log file

### ISSUE THREAD

**Issue by jonleverrier** [verbb/timber#2]
### Describe the bug

Great plugin!

I've added custom logging to one of my modules. I used the following guide:
https://putyourlightson.com/articles/adding-logging-to-craft-plugins-with-monolog

When I try and view the log file, Timber throws the following error:

```
AxiosError: Request failed with status code 500

yii2mod\query\ArrayQuery::from(): Argument #1 ($data) must be of type array, bool given, called in /var/www/html/craft/vendor/verbb/timber/src/services/Service.php on line 56
/var/www/html/craft/vendor/yii2mod/yii2-array-query/ArrayQuery.php:103
/var/www/html/craft/vendor/verbb/timber/src/services/Service.php:56
```

I've noticed that the Sprig log file (if installed), also throws this error. So does:

- web.log (but not the files with a date stamp)
- queue.log (but not the files with a date stamp)
- console.log (but not the files with a date stamp)

### Steps to reproduce

1. Go to Timber in Utilities 
2. Select queue.log, notice how it throws an error
3. Select a queue.log with a date stamp (queue-2023-03-17.log as an example), notice how no error is thrown

### Craft CMS version

4.4.3

### Plugin version

1.0.1

### Multi-site?

No

### Additional context

Local environment using DDEV

**Comment by engram-design** [comment]
I'll have to have a look at that, but likely down to the parsing of the log file. Would you mind sending your log file that throws an error to `support@verbb.io` so I can take a look? All the log file examples I've checked with seem okay (including Sprig).

**Comment by jonleverrier** [comment]
Sent!

**Comment by engram-design** [comment]
So this seems to be down to the format used by that log file. I'm not exactly sure _how_ that's different to mine:

### console.log

**Mine**
```
2023-03-01 22:04:45 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=craft4_craft;port=3306 {"memory":13980176}
```

**Yours**
```
2022-01-03 15:29:04 [-][-][-][info][yii\db\Connection::open] Opening DB connection: mysql:host=mariadb-10.3-3306.database.nitro;dbname=db_craftcommerce;port=3306
```

I'm wondering, were these logs generated in an older version of Craft? From the looks of things, that seems correct, as the log format was changed from `[info]` to `[console.INFO]` (for example) in Craft 4.

Which would also make sense, as log files are now no longer non-date segmented in their filenames in Craft 4. So I'd say you're looking at old logs from Craft 3! I'll see what I can do to cater for that though.

**Comment by engram-design** [comment]
As for the `ondemand` log you sent through, can I ask what this is from? Is it a plugin, or a system process? That indeed doesn't follow a log pattern I've seen, so it won't match any log entries. I can certainly add handling for that, but just wanted to check.

**Comment by jonleverrier** [comment]
> I'm wondering, were these logs generated in an older version of Craft? From the looks of things, that seems correct, as the log format was changed from `[info]` to `[console.INFO]` (for example) in Craft 4.

This makes perfect sense. I thought, as an example, `console.log` was the latest output, and `console-<date>.log` were archived log files, but that doesn't seem to be the case. Doh!

The `ondemand` log file is custom. I have control over the output. I didn't release it had to follow a particular format.

Thanks for all your help Josh!

**Comment by engram-design** [comment]
I've added some tentative Craft 3 log handling for the next release, but it's not really the goal of the plugin to support Craft 3 logs - they're quite different and don't adhere to Monolog like Craft 4 does.

The format in particular to allow us to parse it effectively. The real requirement is to follow Monolog's format, but we probably need to provide extensibility events to add your own Regex patterns.

For your `ondemand` logs, it's pretty basic:

```
/^(?P<datetime>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<message>.*)/s
```

But we still don't handle that. I'll give that some thought.

**Comment by jonleverrier** [comment]
Thanks Josh. Closing this issue as it seems more user error/question based.

**Comment by engram-design** [comment]
FYI, I've also added the pattern for your `ondemand` file for the time being!
